name: iwae
dependencies:
    - python==2.7.10
    - numpy
    - scipy
    - matplotlib
    - pip:
        - progressbar
        - ipdb
        - git+https://github.com/Theano/Theano.git@9d0c52b9254c0d30dacbf1e2a231112ee3e3b99a#egg=Theano
        - git+https://github.com/Lasagne/Lasagne.git@19b9d958507e7300e355d7cd1a6bbff2c7726c07#egg=Lasagne
